### ISSUE TITLE
Translations is invalid

### ISSUE THREAD

**Issue by connecticus** [greendog/refinerycms-snippets#1]
last Refinery 3.0.0 from github

Snippet isn't saved - error: Translations is invalid

trace:
Started POST "/refinery/snippets" for 127.0.0.1 at 2014-11-30 19:30:27 -0800
Processing by Refinery::Snippets::Admin::SnippetsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"HOJNsLSrPSEbWmJpy9O5d9dzAAYB3NxtiUBilbLoe0s=", "switch_locale"=>"", "snippet"=>{"title"=>"slider", "body"=>"<p>slide</p>"}, "locale"=>:en}
  Refinery::Role Load (0.3ms)  SELECT  "refinery_roles".\* FROM "refinery_roles"  WHERE "refinery_roles"."title" = 'Refinery'  ORDER BY "refinery_roles"."id" ASC LIMIT 1
  Refinery::User Exists (0.1ms)  SELECT  1 AS one FROM "refinery_users" INNER JOIN "refinery_roles_users" ON "refinery_users"."id" = "refinery_roles_users"."user_id" WHERE "refinery_roles_users"."role_id" = ? LIMIT 1  [["role_id", 1]]
  Refinery::User Load (0.3ms)  SELECT  "refinery_users".\* FROM "refinery_users"  WHERE "refinery_users"."id" = 1  ORDER BY "refinery_users"."id" ASC LIMIT 1
  Refinery::UserPlugin Load (0.1ms)  SELECT "refinery_user_plugins".\* FROM "refinery_user_plugins"  WHERE "refinery_user_plugins"."user_id" = ?  ORDER BY position ASC  [["user_id", 1]]
  Refinery::Role Load (0.1ms)  SELECT "refinery_roles".\* FROM "refinery_roles" INNER JOIN "refinery_roles_users" ON "refinery_roles"."id" = "refinery_roles_users"."role_id" WHERE "refinery_roles_users"."user_id" = ?  [["user_id", 1]](0.1ms)  begin transaction
  Refinery::Snippets::Snippet Exists (0.2ms)  SELECT  1 AS one FROM "refinery_snippets"  WHERE "refinery_snippets"."title" = 'slider' LIMIT 1
  CACHE (0.0ms)  SELECT  1 AS one FROM "refinery_snippets"  WHERE "refinery_snippets"."title" = 'slider' LIMIT 1
   (0.1ms)  rollback transaction
  CACHE (0.0ms)  SELECT  1 AS one FROM "refinery_snippets"  WHERE "refinery_snippets"."title" = 'slider' LIMIT 1
  CACHE (0.0ms)  SELECT  1 AS one FROM "refinery_snippets"  WHERE "refinery_snippets"."title" = 'slider' LIMIT 1
  Rendered /home/stas/.rvm/rubies/ruby-2.1.4/lib/ruby/gems/2.1.0/bundler/gems/refinerycms-ed5f56f9a1c7/core/app/views/refinery/admin/_error_messages.html.erb (0.7ms)
  Rendered /home/stas/.rvm/rubies/ruby-2.1.4/lib/ruby/gems/2.1.0/bundler/gems/refinerycms-ed5f56f9a1c7/core/app/views/refinery/admin/_locale_picker.html.erb (0.1ms)
  Rendered /home/stas/.rvm/rubies/ruby-2.1.4/lib/ruby/gems/2.1.0/bundler/gems/refinerycms-ed5f56f9a1c7/core/app/views/refinery/admin/_wysiwyg.html.erb (0.7ms)
  Rendered /home/stas/.rvm/rubies/ruby-2.1.4/lib/ruby/gems/2.1.0/bundler/gems/refinerycms-ed5f56f9a1c7/core/app/views/refinery/admin/_form_actions.html.erb (1.8ms)
  Rendered vendor/extensions/refinerycms-snippets/app/views/refinery/snippets/admin/snippets/_form.html.erb (27.4ms)
  Rendered vendor/extensions/refinerycms-snippets/app/views/refinery/snippets/admin/snippets/new.html.erb within layouts/refinery/admin (29.0ms)
  Rendered /home/stas/.rvm/rubies/ruby-2.1.4/lib/ruby/gems/2.1.0/bundler/gems/refinerycms-ed5f56f9a1c7/core/app/views/refinery/_html_tag.html.erb (0.1ms)
  Rendered /home/stas/.rvm/rubies/ruby-2.1.4/lib/ruby/gems/2.1.0/bundler/gems/refinerycms-ed5f56f9a1c7/core/app/views/refinery/admin/_javascripts.html.erb (317.2ms)
  Rendered /home/stas/.rvm/rubies/ruby-2.1.4/lib/ruby/gems/2.1.0/bundler/gems/refinerycms-ed5f56f9a1c7/core/app/views/refinery/admin/_head.html.erb (381.7ms)
  Rendered /home/stas/.rvm/rubies/ruby-2.1.4/lib/ruby/gems/2.1.0/bundler/gems/refinerycms-ed5f56f9a1c7/core/app/views/refinery/_site_bar.html.erb (1.3ms)
  Rendered /home/stas/.rvm/rubies/ruby-2.1.4/lib/ruby/gems/2.1.0/bundler/gems/refinerycms-ed5f56f9a1c7/core/app/views/refinery/admin/_menu.html.erb (2.6ms)
  Rendered /home/stas/.rvm/rubies/ruby-2.1.4/lib/ruby/gems/2.1.0/bundler/gems/refinerycms-ed5f56f9a1c7/core/app/views/refinery/_no_script.html.erb (0.3ms)
  Rendered /home/stas/.rvm/rubies/ruby-2.1.4/lib/ruby/gems/2.1.0/bundler/gems/refinerycms-ed5f56f9a1c7/core/app/views/refinery/_message.html.erb (0.1ms)
Completed 200 OK in 470ms (Views: 444.8ms | ActiveRecord: 1.4ms)

**Comment by connecticus** [comment]
Bug related with this commit - https://github.com/refinery/refinerycms-i18n/commit/18aae0942cdee787a8701203f0ae325a0bf817b9

I rollback to previous commit and now work.

**Comment by jitscar** [comment]
fixed https://github.com/greendog/refinerycms-snippets/commit/cf697b63e0e596f80747b0adfa7d2b25dcd07744
