### ISSUE TITLE
refinery edge + refinerycms-snippets

### ISSUE THREAD

**Issue by connecticus** [greendog/refinerycms-snippets#3]
ActionView::Template::Error (undefined method `convert_title_to_id' for #<Refinery::Pages::PagePartSectionPresenter:0x007f2bcc1ac5a8>):
    1: <%= render_content_page(@page, {
    2:       :hide_sections => local_assigns[:hide_sections],
    3:       :can_use_fallback => !local_assigns[:show_empty_sections] && !local_assigns[:remove_automatic_sections]
    4:     }) %>
  app/controllers/refinery/pages_controller.rb:42:in`show'

**Comment by balexandr** [comment]
I am getting this too. Any headway made?

**Comment by connecticus** [comment]
Still no. Refinery gets a lot of changes. In such conditions it is difficult to maintain plug-ins.

**Comment by balexandr** [comment]
Yeah I get that. Oh well. I'll just disable snippets for the time being then.

**Comment by connecticus** [comment]
I will try to solve this in couple days. If it  successful - let you know.
